### ISSUE TITLE
react native version issue

### ISSUE THREAD

**Issue by BorisKingma** [JOikarinen/ReactNativePolarBleSdkExample#1]
Hello,

I tried to run your code by copy-pasting the files in a new rn project; however unfortunately the project build fails both for Android and iOS.

I suspect it has to do with an upgrade of react native? in your code i see 0.68.2, whereas I understand 0.71 is current.

would it be possible to upload an upgraded version of your code?

**Comment by BorisKingma** [comment]
The issue is solved by following the instructions on PolarOfficial, however, the example given in this git does not work with SDK 5.0.0(current PolarSDK).

**Comment by G-Rgn** [comment]
Hello @BorisKingma, I am quite new to react native and I wonder how to get H9 data in a simple mobile app both for Android and iOS. I tried to copy paste this git just like you did few months ago but it didn't work either. Should i just start over from PolarOfficial and create bridge as it is present in this git ?
